#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  setup.sh --vault <vault-path> --remote <github-remote-url> --include <folder1,folder2,...> [--branch main] [--message "..."] [--dry-run]

Example:
  setup.sh \
    --vault "/Users/mac/Desktop/obsidian" \
    --remote "https://github.com/yourname/obsidian.git" \
    --include "project,SKILL,Learing"

This script uses an allowlist .gitignore:
  - ignore the whole vault by default
  - include only selected folders
  - do not include .obsidian unless explicitly passed in --include
USAGE
}

VAULT_PATH=""
REMOTE_URL=""
INCLUDE_CSV=""
BRANCH="main"
COMMIT_MESSAGE="sync selected Obsidian folders"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --vault)
      VAULT_PATH="${2:-}"
      shift 2
      ;;
    --remote)
      REMOTE_URL="${2:-}"
      shift 2
      ;;
    --include)
      INCLUDE_CSV="${2:-}"
      shift 2
      ;;
    --branch)
      BRANCH="${2:-}"
      shift 2
      ;;
    --message)
      COMMIT_MESSAGE="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "$VAULT_PATH" || -z "$REMOTE_URL" || -z "$INCLUDE_CSV" ]]; then
  echo "Missing required argument." >&2
  usage
  exit 2
fi

if ! command -v git >/dev/null 2>&1; then
  echo "git is required but was not found." >&2
  exit 1
fi

if [[ ! -d "$VAULT_PATH" ]]; then
  echo "Vault path does not exist: $VAULT_PATH" >&2
  exit 1
fi

cd "$VAULT_PATH"

IFS=',' read -r -a RAW_INCLUDES <<< "$INCLUDE_CSV"
INCLUDES=()
for item in "${RAW_INCLUDES[@]}"; do
  cleaned="$(printf '%s' "$item" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s#^/##;s#/$##')"
  if [[ -n "$cleaned" ]]; then
    INCLUDES+=("$cleaned")
  fi
done

if [[ ${#INCLUDES[@]} -eq 0 ]]; then
  echo "No folders were provided in --include." >&2
  exit 1
fi

MISSING=()
for folder in "${INCLUDES[@]}"; do
  if [[ ! -e "$folder" ]]; then
    MISSING+=("$folder")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "These included paths do not exist inside the vault:" >&2
  printf '  - %s\n' "${MISSING[@]}" >&2
  exit 1
fi

TMP_GITIGNORE="$(mktemp)"
{
  echo "# Generated by obsidian-git-sync selected-folder setup"
  echo "# Default: ignore everything, then allow only selected folders."
  echo "*"
  echo "!.gitignore"
} > "$TMP_GITIGNORE"

emit_allow_rules() {
  local target="$1"
  local path_accum=""
  IFS='/' read -r -a parts <<< "$target"
  for part in "${parts[@]}"; do
    if [[ -z "$path_accum" ]]; then
      path_accum="$part"
    else
      path_accum="$path_accum/$part"
    fi
    echo "!$path_accum/"
  done
  echo "!$target/**"
}

for folder in "${INCLUDES[@]}"; do
  emit_allow_rules "$folder" >> "$TMP_GITIGNORE"
done

cat >> "$TMP_GITIGNORE" <<'EOF'

# Keep common local/system files out.
.DS_Store
Thumbs.db
EOF

echo "Vault: $VAULT_PATH"
echo "Remote: $REMOTE_URL"
echo "Branch: $BRANCH"
echo "Selected folders:"
printf '  - %s\n' "${INCLUDES[@]}"
echo
echo "Generated .gitignore:"
cat "$TMP_GITIGNORE"
echo

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "Dry run only. No files changed."
  rm -f "$TMP_GITIGNORE"
  exit 0
fi

if [[ ! -d .git ]]; then
  git init
fi

if [[ -f .gitignore ]]; then
  backup=".gitignore.backup.$(date +%Y%m%d-%H%M%S)"
  cp .gitignore "$backup"
  echo "Existing .gitignore backed up to $backup"
fi

mv "$TMP_GITIGNORE" .gitignore

git branch -M "$BRANCH"

if git remote get-url origin >/dev/null 2>&1; then
  git remote set-url origin "$REMOTE_URL"
else
  git remote add origin "$REMOTE_URL"
fi

git add .gitignore
for folder in "${INCLUDES[@]}"; do
  git add "$folder"
done

echo
echo "Staged changes:"
git status --short
echo

if git diff --cached --quiet; then
  echo "Nothing to commit."
else
  git commit -m "$COMMIT_MESSAGE"
fi

git push -u origin "$BRANCH"

echo
echo "Done. Selected Obsidian folders are synced to GitHub."

